default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: agency_development
  username: agency
  password: agency
  host: localhost

test:
  <<: *default
  database: agency_test
  username: agency
  password: agency
  host: localhost

production:
  <<: *default
  database: agency_production
